alumnos:
    resource: "@AlumnosBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#Importar la configuracion para las rutas de FOSUserBundle
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"