alumnos:
    resource: "@AlumnosBundle/Resources/config/routing.yml"
    prefix:   /

#Importar la configuracion para las rutas de FOSUserBundle
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#Importar las rutas de JsRouting
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
 
#Ruta de la api
api:
    type: rest
    resource: "@AlumnosBundle/Resources/config/rest.yml"